name: Sam Engel
favicon: null
layout_spectrum: 0.8863999366294593
typography_spectrum: 0.861467627575621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4660027117934078
  lightness: 0.0035119391977787018
  saturation: 0.40487937862053514
  rhythmicContrast: 0.9280255874618888
purpose: []
