name: Sam Engel
favicon: null
layout_spectrum: 0.8863999366294593
typography_spectrum: 0.861467627575621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#a4d4fc'
    - '#110e1c'
    - '#454d61'
    - '#938a7d'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
